replicaCount: 2

backend:
  image: yourdockerhubuser/myapp-backend:latest
  servicePort: 8000

frontend:
  image: yourdockerhubuser/myapp-frontend:latest
  servicePort: 80

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: example.com
      paths:
        - path: /api(/|$)(.*)
          service: backend-service
          servicePort: 8000
        - path: /(.*)
          service: frontend-service
          servicePort: 80
