apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-fastapi.fullname" . }}-backend
spec:
  selector:
    app: backend
  ports:
  - port: {{ .Values.backend.servicePort }}
    targetPort: {{ .Values.backend.servicePort }}
